## Regional and sectoral structures of the Chinese economy:A network perspective from multi-regional input-output tables

A multi-regional input--output table (MRIOT) containing the transactions among the region-sectors in an economy defines a weighted and directed network. Using network analysis tools, we analyze the regional and sectoral structure of the Chinese economy with the province-sector MRIOTs of China in 2007 and 2012. Global analyses are done with network topology measures. Growth-driving province-sector clusters are identified with community detection methods. Influential province-sectors are ranked by weighted PageRank scores. The results have revealed a few interesting and telling insights. The level of inter-province activities increased with the rapid growth of the national economy, but not as fast as that of intra-province economic activities. Regional community structures were deeply associated with geographical factors. The community heterogeneity across the regions was high and the regional fragmentation increased during the study period. Quantified metrics assessing the relative importance of the province-sectors in the national economy echo the national and regional economic development policies to a certain extent.

``` bib
@article{wang2021regional,
  title = {Regional and Sectoral Structures of the {C}hinese Economy: {A} Network Perspective from Multi-Regional Input-Output Tables},
  author = {Wang, Tao and Xiao, Shiying and Yan, Jun and Zhang, Panpan},
  journal = {Physica A: Statistical Mechanics and its Applications},
  volume = 581,
  pages = 126196,
  year = 2021,
  publisher = {Elsevier}
}
```
